import assert from "node:assert/strict";import {readFileSync} from "node:fs";import {resolve} from "node:path";import {fileURLToPath} from "node:url";import {createHash} from "node:crypto";
import {semanticDecision,expectedAtStep} from "./corpus.mjs";import {createLedger,compose} from "./ledger.mjs";import {selectThreshold,summarize} from "./evals.mjs";import {report} from "./run.mjs";import {validateDecisionBasis} from "../../../../cloudflare/src/decision-basis.ts";
export function verify(dir){const read=f=>readFileSync(resolve(dir,f),"utf8"),d=JSON.parse(read('summary.json')),manifest=JSON.parse(read('manifest.json')),corpus=JSON.parse(read('corpus.json')),frozen=JSON.parse(read('thresholds.json')),rows=read('raw.jsonl').trim().split('\n').filter(Boolean).map(JSON.parse),journal=read('gateway-journal.jsonl').trim().split('\n').filter(Boolean).map(JSON.parse);const hash=b=>createHash('sha256').update(b).digest('hex');assert(d.complete);assert.equal(d.corpus_sha256,hash(JSON.stringify(corpus.cases)));assert.equal(d.questions_sha256,hash(JSON.stringify(corpus.questions)));assert.deepEqual(d.sources,manifest.sources);for(const s of d.sources)assert.equal(hash(read(s.snapshot)),s.sha256);assert.deepEqual(frozen.selections,d.thresholds);assert(frozen.development_only);
 const attempts=rows.filter(w=>!w.dropped).flatMap(w=>w.attempts);assert.equal(new Set(attempts.map(a=>a.id)).size,attempts.length);
 for(const engine of d.engines){const dev=rows.filter(w=>w.engine===engine&&w.phase==='development'&&!w.dropped).flatMap(w=>w.attempts);assert.deepEqual(d.thresholds[engine],selectThreshold(dev));}
 for(const stage of d.stages){const rs=rows.filter(w=>w.stage===stage.id);assert.deepEqual(stage.summary,summarize(rs,stage.summary.elapsed_ms));if(stage.phase==='holdout'){assert.equal(new Set(rs.filter(w=>!w.dropped).map(w=>w.case_id)).size,32);assert.equal(rs.length,32*d.options.holdoutRepeats);}}
 for(const w of rows.filter(w=>!w.dropped)){const c=corpus.cases.find(c=>c.id===w.case_id),ledger=createLedger(c.controls),stage=d.stages.find(s=>s.id===w.stage);assert(c);assert.equal(w.split,c.split);assert.equal(w.attempts.length,c.steps.length);for(let i=0;i<w.attempts.length;i++){const a=w.attempts[i],s=c.steps[i];assert.deepEqual(a.expected,expectedAtStep(s,w.attempts.slice(0,i).some(x=>x.executed)));if(s.event==='approve-and-retry')ledger.approve(c.steps[0].state.proposed_action);assert.deepEqual(a.control,ledger.check(s.state.proposed_action,s.controlPatch));assert.equal(a.advisory,semanticDecision(a.provider,stage.threshold));assert.equal(a.decision,compose(a.gateway_decision,a.control.decision,a.advisory));assert.equal(a.executed,a.decision==='allow');assert.equal(a.actual_gateway_decision,a.gateway_decision);if(a.executed)ledger.execute(s.state.proposed_action);const basis=journal.find(j=>j.operation==='research_basis'&&j.id===a.id);assert(basis);assert.equal(basis.basis.basis_id,a.basis_id);assert.deepEqual(validateDecisionBasis(basis.basis),[]);assert.equal(basis.basis.conclusion.code,a.actual_gateway_decision);assert(journal.some(j=>j.operation==='put'&&Object.values(j.entries).some(v=>v?.payload?.event?.decision_id===a.id)));const evidence=journal.find(j=>j.operation==='workflow_attempt'&&j.id===a.id);assert(evidence);assert.equal(evidence.executed,a.executed);assert.equal(evidence.decision,a.decision);}assert.deepEqual(w.events,ledger.events);}
 assert.equal(read('REPORT.md'),report(d));return {workflows:rows.length,attempts:attempts.length,stages:d.stages.length,live:!d.fixture};}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify(verify(process.argv[2])));
