// Optional real-browser acceptance suite. Install Playwright and its Chromium
// browser, or point PLAYWRIGHT_MODULE at an existing installation.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || "playwright");
import { createServer } from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import assert from 'node:assert/strict';
import worker from '../src/worker.ts';
import { RegistryCatalog, parseCatalogQuery } from '../src/mcp-registry.ts';
const db = new DatabaseSync(':memory:');
let alarm: number | null = null;
const storage = { sql: { exec(q: string,...v: any[]) { const a=db.prepare(q).all(...v); return {toArray:()=>a}; } }, transactionSync(fn:()=>unknown){return fn();},async setAlarm(n:number){alarm=n;},async getAlarm(){return alarm;} };
const entry=(name:string,description:string, remotes:unknown[]=[{type:'streamable-http',url:`https://${name}.example/mcp`}])=>({server:{name:`org.example/${name}`,title:name,description,version:'1',remotes,websiteUrl:'https://example.com/docs'},_meta:{'io.modelcontextprotocol.registry/official':{status:'active',isLatest:true}}});
const catalog=new RegistryCatalog(storage,async()=>Response.json({servers:[entry('letters','Deliver messages to email accounts'), entry('warehouse','Query a SQL database'),entry('local-files','Read documents from local files',[]),entry('markup','<img src=x onerror=alert(1)> Email'),...Array.from({length:22},(_,i)=>entry(`mail${i}`,'Email delivery',[{type:'streamable-http',url:`https://mail${i}.example/mcp`,headers:[{name:'X-API-Key',isSecret:true}]}]))], metadata:{}}));
await catalog.alarm();
let posts=0, failure=false, delayed=false, approvalFailure=false, connectDelay=false, sessionFailure=0;
const approvals: any[] = [], posted: any[] = [], inspections: any[] = [], inspectionRequests: any[] = [];
let inspectionFailure=false, inspectionDelay=false;
const inspectionReport=(endpoint:string)=>({endpoint,checkedAt:new Date().toISOString(),protocol:'2025-11-25',authentication:'oauth',visibility:'authentication-required',toolCount:0,tools:[],providers:[{issuer:'https://login.vendor.com',metadata:'https://login.vendor.com/.well-known/oauth-authorization-server',verified:true,pkce:true}],scopes:['files:read','files:write'],challengedScopes:['files:read'],evidence:[{url:endpoint,status:401}],findings:[{level:'review',title:'OAuth discovered · login not supported yet',detail:'OAuth metadata was discovered; no tokens were requested.'},{level:'review',title:'Limited assessment, not a safety certification',detail:'Account-specific tools and backend behavior remain unknown.'},{level:'review',title:'<img src=x onerror=alert(1)>',detail:'Provider text remains untrusted.'}]});
const endpointAccess = {deployment:['https://manual.example/mcp'],workspace:approvals};
const server=createServer(async(req,res)=>{
 const u=new URL(req.url!,'http://127.0.0.1');
 let value:any;
 if(sessionFailure&&u.pathname.startsWith('/api/')){res.statusCode=sessionFailure;if(sessionFailure===302)res.setHeader('location','/sign-in-fixture');res.setHeader('content-type','application/json');res.end(JSON.stringify({error:'Sign in required'}));return;}
 if(['/agents','/assets/agents.css','/assets/agents.js','/favicon.png','/favicon.ico','/csp-probe'].includes(u.pathname)){
   const response=await worker.fetch(new Request(new URL(u.pathname==='/csp-probe'?'/agents':u.pathname,u.origin)),{CONSOLE_ENVIRONMENT:'development',CONSOLE_ENABLE_MOCK_IDENTITY:'true',CONSOLE_MOCK_TENANT_ID:'a',CONSOLE_MOCK_SUBJECT:'fixture-owner'});
   res.statusCode=response.status;response.headers.forEach((v,k)=>res.setHeader(k,v));
   if(u.pathname==='/csp-probe')res.end((await response.text()).replace('</head>','<link rel="stylesheet" href="/assets/csp-probe.css"><script src="https://example.invalid/probe.js"></script></head>'));
   else res.end(Buffer.from(await response.arrayBuffer()));return;
 }
 if(u.pathname==='/assets/csp-probe.css'){res.setHeader('content-type','text/css');res.end('@font-face{font-family:Probe;src:url(data:font/woff2;base64,d09GMg==)}body{font-family:Probe}');return;}
 if(u.pathname==='/api/console/session')value={email:'owner+<img src=x onerror=alert(1)>@example.com',subject:'owner-subject',tenant_id:'a',memberships:[{tenant:{tenant_id:'a',display_name:'Test workspace'},membership:{role:'owner'}},{tenant:{tenant_id:'b',display_name:'Second workspace'},membership:{role:'viewer'}},{tenant:{tenant_id:'c',display_name:'Operator workspace'},membership:{role:'operator'}}]};
 else if(u.pathname.endsWith('/state'))value={connections:[],agents:[],runs:[],inspections:u.pathname.includes('/a/')?inspections:[],endpointAccess:u.pathname.includes('/a/')?endpointAccess:{deployment:endpointAccess.deployment,workspace:[]}};
 else if(u.pathname.endsWith('/catalog')){if(delayed)await new Promise(r=>setTimeout(r,300)); if(failure){res.statusCode=503;value={error:'Registry discovery is unavailable. Enter an endpoint manually.'};}else value=await catalog.search(parseCatalogQuery(u.searchParams));}
 else if(u.pathname.endsWith('/inspect-endpoint')&&req.method==='POST'){
   let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);inspectionRequests.push(body);if(inspectionDelay)await new Promise(r=>setTimeout(r,350));
   if(inspectionFailure){res.statusCode=429;value={error:'The daily workspace limit has been reached. Try again tomorrow.'};}else{value=inspectionReport(body.endpoint);const old=inspections.findIndex(r=>r.endpoint===body.endpoint);if(old>=0)inspections.splice(old,1);inspections.push(value);}
 }
 else if(req.method==='POST'){
   if(connectDelay&&u.pathname.endsWith('/connect'))await new Promise(r=>setTimeout(r,350));
   posts++;let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);posted.push({path:u.pathname,body});value={};
   if(u.pathname.endsWith('/approve-endpoint')){if(approvalFailure){res.statusCode=400;value={error:'This endpoint could not be verified as public.'};}else approvals.push({endpoint:body.endpoint,approvedBy:'owner@example.com',approvedAt:new Date().toISOString()});}
   if(u.pathname.endsWith('/remove-endpoint'))approvals.splice(approvals.findIndex(a=>a.endpoint===body.endpoint),1);
 }
 else{res.statusCode=404;value={};}
 res.setHeader('content-type','application/json');res.end(JSON.stringify(value));
});
await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true, ...(process.env.PLAYWRIGHT_CHANNEL ? {channel:process.env.PLAYWRIGHT_CHANNEL} : {})});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.addInitScript(()=>{(window as any).cspViolations=[];document.addEventListener('securitypolicyviolation',e=>(window as any).cspViolations.push({directive:e.effectiveDirective,uri:e.blockedURI}));});
try {
const address = server.address() as {port:number};
await page.goto(`http://127.0.0.1:${address.port}/agents`);await page.locator('#catalog-status').filter({hasText:'26 matching servers'}).waitFor();
assert.equal(await page.locator('#account-identity').innerText(),'owner+<img src=x onerror=alert(1)>@example.com');assert.equal(await page.locator('.account img').count(),0);assert.equal(await page.locator('#account-role').innerText(),'owner');
assert.equal(await page.getByRole('link',{name:'Log out',exact:true}).getAttribute('href'),'/cdn-cgi/access/logout');assert.equal(await page.locator('#account-login').isVisible(),false);assert.equal(posts,0);
await page.screenshot({path:'/tmp/agentaction-account-desktop.png'});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/agentaction-account-mobile.png'});await page.setViewportSize({width:1440,height:1000});
const precheck=page.locator('#precheck-run'), precheckField=page.locator('#precheck-endpoint');
await precheckField.fill('https://letters.example/mcp');await page.locator('[name=token]').fill('DO-NOT-SEND-PRECHECK');await precheck.click();await page.locator('#precheck-results h4').filter({hasText:'OAuth discovered'}).waitFor();
assert.deepEqual(inspectionRequests.at(-1),{endpoint:'https://letters.example/mcp',protocol:'2025-03-26'});assert.equal(posts,0);assert.equal(approvals.length,0);assert.equal(await page.locator('#precheck-results img').count(),0);assert.match(await page.locator('#precheck-results').innerText(),/login not supported yet/);assert.match(await page.locator('#precheck-results').innerText(),/requires authentication/);assert.match(await page.locator('#precheck-results').innerText(),/files:write/);
await page.reload();await page.locator('#catalog-status').filter({hasText:'26 matching servers'}).waitFor();await page.locator('#precheck-results h4').filter({hasText:'OAuth discovered'}).waitFor();assert.equal(await precheckField.inputValue(),'https://letters.example/mcp');
await page.setViewportSize({width:390,height:844});await page.locator('#endpoint-precheck').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/agentaction-precheck-mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.locator('#endpoint-precheck').screenshot({path:'/tmp/agentaction-precheck-desktop.png'});
await precheckField.fill('https://different.example/mcp');assert.equal(await page.locator('#precheck-results h4').count(),0);
inspectionDelay=true;await precheck.click();assert.equal(await precheck.getAttribute('aria-busy'),'true');await precheckField.fill('https://new.example/mcp');await page.waitForTimeout(450);assert.equal(await page.locator('#precheck-results h4').count(),0);assert.equal(await precheck.getAttribute('aria-busy'),null);inspectionDelay=false;
inspectionFailure=true;await precheck.click();await page.locator('#precheck-status').filter({hasText:'Pre-check failed:'}).waitFor();assert.equal(await precheck.isEnabled(),true);inspectionFailure=false;
await page.locator('#catalog-query').fill('letters');await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-status').filter({hasText:'1 matching servers'}).waitFor();await page.getByRole('button',{name:'Pre-check',exact:true}).click();await page.locator('#precheck-results h4').filter({hasText:'OAuth discovered'}).waitFor();assert.equal(await precheckField.inputValue(),'https://letters.example/mcp');assert.match(await page.locator('[data-inspection-endpoint]').innerText(),/OAuth discovered/);
await page.locator('#workspace').selectOption('b');await page.locator('#status').filter({hasText:'Workspace ready · viewer'}).waitFor();assert.equal(await page.locator('#precheck-results h4').count(),0);assert.equal(await precheck.isDisabled(),true);await page.locator('#workspace').selectOption('a');await page.locator('#status').filter({hasText:'Workspace ready · owner'}).waitFor();
await page.locator('#catalog-query').fill('');await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-status').filter({hasText:'26 matching servers'}).waitFor();
await page.getByRole('button',{name:'Show more servers'}).click();await page.waitForFunction(()=>document.querySelectorAll('#catalog-results article').length===26);
const authFilter=page.getByRole('combobox',{name:'Authentication',exact:true});
assert.equal(await authFilter.locator('option').count(),5);
const capabilityBox=await page.locator('#catalog-capability').boundingBox(), authBox=await authFilter.boundingBox();assert.ok(capabilityBox&&authBox&&Math.abs(capabilityBox.y-authBox.y)<2&&authBox.x>capabilityBox.x);
await authFilter.selectOption('api-key');await page.locator('#catalog-capability').selectOption('email');await page.locator('#catalog-query').fill('send emails');await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-status').filter({hasText:'22 matching servers'}).waitFor();
assert.equal(await page.locator('#catalog-results article').count(),20);assert.equal(await page.getByText('Declared authentication: API key',{exact:true}).count(),20);assert.equal(await page.locator('#catalog-results button').filter({hasText:'Use this server'}).count(),0);
// Editing controls before Show more must not change the submitted result set.
await authFilter.selectOption('unspecified');await page.getByRole('button',{name:'Show more servers'}).click();await page.waitForFunction(()=>document.querySelectorAll('#catalog-results article').length===22);assert.equal(await page.getByText('Declared authentication: API key',{exact:true}).count(),22);
await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-status').filter({hasText:'2 matching servers'}).waitFor();assert.equal(await page.getByText('Declared authentication: Not specified',{exact:true}).count(),2);
await authFilter.selectOption('authorization-header');await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-status').filter({hasText:'0 matching servers'}).waitFor();await page.getByText('No matching servers.',{exact:false}).waitFor();assert.equal(await page.locator('#catalog-more').isHidden(),true);
await page.setViewportSize({width:390,height:844});await page.locator('#catalog-search').scrollIntoViewIfNeeded();const mobileCapability=await page.locator('#catalog-capability').boundingBox(), mobileAuth=await authFilter.boundingBox();assert.ok(mobileCapability&&mobileAuth&&mobileAuth.y>mobileCapability.y);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/agentaction-auth-filter-mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/tmp/agentaction-auth-filter-desktop.png'});
assert.match(await page.locator('#catalog-auth-help').innerText(),/Not specified does not mean no authentication/);assert.match(await page.locator('#catalog-auth-help').innerText(),/pricing/);assert.equal(posts,0);
await authFilter.selectOption('');await page.locator('#catalog-capability').selectOption('');
await page.locator('#catalog-query').fill('send emails');await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-status').filter({hasText:'24 matching servers'}).waitFor();
assert.equal(await page.locator('#catalog-results img').count(),0);
await page.locator('#catalog-query').fill('letters');await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-status').filter({hasText:'1 matching servers'}).waitFor();
await page.locator('[name=token]').fill('OLD-CREDENTIAL');await page.locator('[name=consent]').check();
await page.getByRole('button',{name:'Use this server'}).click();
assert.equal(await page.locator('[name=endpoint]').inputValue(),'https://letters.example/mcp');assert.equal(await page.locator('[name=label]').inputValue(),'letters');assert.equal(await page.locator('[name=token]').inputValue(),'');assert.equal(await page.locator('[name=consent]').isChecked(),false);assert.equal(posts,0);
const connectButton=page.locator('#connect button[type=submit]'), approveButton=page.getByRole('button',{name:'Approve endpoint for workspace'});
assert.equal(await connectButton.isDisabled(),true);assert.equal(await connectButton.evaluate(el=>getComputedStyle(el).cursor),'not-allowed');assert.equal(await connectButton.getAttribute('aria-busy'),null);assert.match(await page.locator('#connect-readiness').innerText(),/Connection blocked:.*Review its exact URL/);assert.equal(await page.locator('#connect-readiness').getAttribute('data-state'),'blocked');assert.match(await page.locator('[data-endpoint-access]').innerText(),/Owner approval required/i);
await page.locator('#endpoint-reviewed').check();await page.locator('[name=endpoint]').fill('https://letters.example/mcp/other');assert.equal(await page.locator('#endpoint-reviewed').isChecked(),false);assert.equal(await approveButton.isDisabled(),true);
await page.setViewportSize({width:390,height:844});await page.locator('[name=endpoint]').fill('https://letters.example/'+ 'long-path-'.repeat(80));await page.locator('#endpoint-review').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/agentaction-endpoint-approval-mobile.png'});await page.setViewportSize({width:1440,height:1000});
await page.locator('[name=endpoint]').fill('https://letters.example/mcp');await page.locator('#endpoint-review').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/agentaction-endpoint-approval-desktop.png'});await page.locator('#endpoint-reviewed').check();approvalFailure=true;await approveButton.click();await page.locator('#status').filter({hasText:'could not be verified'}).waitFor();assert.equal(await connectButton.isDisabled(),true);assert.equal(await approveButton.getAttribute('aria-busy'),null);approvalFailure=false;
await page.locator('[name=token]').fill('DO-NOT-SEND-ON-APPROVAL');await approveButton.click();await page.locator('#status').filter({hasText:'Endpoint approved'}).waitFor();assert.deepEqual(posted.at(-1).body,{endpoint:'https://letters.example/mcp',reviewed:true});assert.equal(await connectButton.isEnabled(),true);assert.equal(await page.locator('#endpoint-review').isHidden(),true);assert.match(await page.locator('[data-endpoint-access]').innerText(),/Enabled for this workspace/i);assert.match(await page.locator('#catalog-results option').innerText(),/— enabled/);
connectDelay=true;await page.locator('[name=consent]').check();await connectButton.click();assert.equal(await connectButton.getAttribute('aria-busy'),'true');assert.equal(await connectButton.innerText(),'Connecting…');assert.equal(await connectButton.evaluate(el=>getComputedStyle(el).cursor),'wait');assert.match(await page.locator('#connect-readiness').innerText(),/Connecting to the server/);await page.locator('#status').filter({hasText:'Connected. Choose'}).waitFor();assert.equal(await connectButton.getAttribute('aria-busy'),null);connectDelay=false;
await page.getByText('Workspace endpoint approvals',{exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Remove workspace approval'}).click();await page.locator('#status').filter({hasText:'Workspace approval removed'}).waitFor();assert.equal(await connectButton.isDisabled(),true);assert.equal(approvals.length,0);
await page.getByRole('button',{name:'Enter an endpoint manually'}).click();assert.equal(await page.locator('[name=endpoint]').inputValue(),'');
await page.locator('[name=label]').fill('Manual');await page.locator('[name=endpoint]').fill('https://manual.example/mcp');await page.locator('[name=consent]').check();await page.getByRole('button',{name:'Connect server',exact:true}).click();await page.locator('#status').filter({hasText:'Connected. Choose'}).waitFor();assert.equal(posts,5);
await page.locator('#catalog-query').fill('query a database');await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-results h3').filter({hasText:'warehouse'}).waitFor();assert.equal(await page.locator('#catalog-results article').count(),1);
await page.locator('#catalog-query').fill('');await page.locator('#catalog-capability').selectOption('files');await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-results h3').filter({hasText:'local-files'}).waitFor();assert.equal(await page.locator('#catalog-results button').count(),0);assert.match(await page.locator('#catalog-results').innerText(),/Setup required outside/i);
await page.locator('#catalog-capability').selectOption('');await page.locator('#catalog-query').fill('nothing-matches');await page.getByRole('button',{name:'Search registry'}).click();await page.getByText('No matching servers.',{exact:false}).waitFor();
failure=true;await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-status').filter({hasText:'unavailable'}).waitFor();assert.equal(await page.locator('[name=endpoint]').isEnabled(),true);failure=false;
await page.locator('#catalog-query').fill('send emails');await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-status').filter({hasText:'24 matching servers'}).waitFor();await page.screenshot({path:'/tmp/agentaction-registry-desktop.png',fullPage:false});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/agentaction-registry-mobile.png',fullPage:false});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.locator('#workspace').selectOption('c');await page.locator('#status').filter({hasText:'Workspace ready · operator'}).waitFor();assert.equal(await page.locator('#account-role').innerText(),'operator');await page.locator('[name=endpoint]').fill('https://unapproved.example/mcp');assert.equal(await page.locator('#endpoint-review').isHidden(),true);assert.equal(await connectButton.isDisabled(),true);assert.match(await page.locator('#connect-readiness').innerText(),/Ask a workspace owner/);await page.locator('[name=endpoint]').fill('https://manual.example/mcp');assert.equal(await connectButton.isEnabled(),true);
await page.locator('#workspace').selectOption('a');await page.locator('#status').filter({hasText:'Workspace ready · owner'}).waitFor();
await authFilter.selectOption('unspecified');delayed=true;await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#workspace').selectOption('b');await page.waitForTimeout(500);assert.equal(await page.locator('#catalog-results article').count(),0);assert.equal(await page.locator('[name=endpoint]').isDisabled(),true);
assert.equal(await authFilter.inputValue(),'unspecified');await page.getByRole('button',{name:'Search registry'}).click();await page.locator('#catalog-status').filter({hasText:'2 matching servers'}).waitFor();assert.equal(await page.getByRole('button',{name:'Use this server'}).first().isDisabled(),true);
assert.match(await page.locator('#connect-readiness').innerText(),/view-only access/);assert.equal(await page.locator('#account-role').innerText(),'viewer');
assert.deepEqual(errors,[
  'Failed to load resource: the server responded with a status of 429 (Too Many Requests)',
  'Failed to load resource: the server responded with a status of 400 (Bad Request)',
  'Failed to load resource: the server responded with a status of 503 (Service Unavailable)'
]);assert.deepEqual(await page.evaluate(()=>(window as any).cspViolations),[]);
assert.equal(await page.evaluate(async()=>{const icon=new Image();icon.src='/favicon.png';await icon.decode();return icon.naturalWidth>0;}),true);
delayed=false;await page.goto(`http://127.0.0.1:${address.port}/csp-probe`);await page.waitForFunction(()=>(window as any).cspViolations.length>=2);
await page.locator('#catalog-status').filter({hasText:'26 matching servers'}).waitFor();
const violations=await page.evaluate(()=>(window as any).cspViolations);assert.ok(violations.some((v:any)=>v.directive==='font-src'&&v.uri==='data'));assert.ok(violations.some((v:any)=>v.directive==='script-src-elem'&&v.uri==='https://example.invalid/probe.js'));
for(const code of [401,302]){
  await page.goto(`http://127.0.0.1:${address.port}/agents`);await page.locator('#catalog-status').filter({hasText:'26 matching servers'}).waitFor();
  await page.locator('[name=token]').fill('TEMPORARY-SECRET');sessionFailure=code;
  await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.locator('#account-login').waitFor({state:'visible'});
  assert.equal(await page.locator('#builder').isHidden(),true);assert.equal(await page.locator('[name=token]').inputValue(),'');assert.equal(await page.locator('#account-logout').isHidden(),true);assert.equal(await page.locator('#workspace').isDisabled(),true);assert.equal(await page.locator('#account-role').innerText(),'Sign in required');assert.match(await page.locator('#account-help').innerText(),/session has expired|signed out/);assert.equal(await page.locator('#account-login').getAttribute('href'),'/agents');
  sessionFailure=0;await page.getByRole('link',{name:'Sign in',exact:true}).click();await page.locator('#catalog-status').filter({hasText:'26 matching servers'}).waitFor();assert.equal(await page.locator('#account-role').innerText(),'owner');assert.equal(await page.locator('#account-login').isHidden(),true);
}
console.log('PASS: persistent visible pre-check findings, OAuth discovery without login, credential exclusion, endpoint races, rate-limit errors, mobile layout and workspace isolation; combined authentication/capability/name filters, declared metadata labels, preserved submitted pagination, filter reset, responsive layout, name/capability search, pagination, safe metadata, selection without connection, cleared secrets/consent, manual connect, unsupported setup, empty/error states, workspace races, viewer/operator access, explicit owner approval without credentials, approval failures, removal, clear blocked/busy states, real CSP headers, decoded favicon, blocked external scripts/data fonts mobile overflow, account identity, workspace roles, safe logout navigation and 401/redirect sign-in recovery.');
} finally { await browser.close();await new Promise<void>(r=>server.close(()=>r()));db.close(); }
