/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1c5ad3a9b6522058fbb6ca12753a3a95)
interface __BaseEnv_Env {
	AGENT_AI: Ai;
	CONSOLE_ENVIRONMENT: "development" | "production";
	CONSOLE_ENABLE_MOCK_IDENTITY?: "true";
	CONSOLE_MOCK_TENANT_ID?: "refund-demo-agent";
	CONSOLE_MOCK_SUBJECT?: "local-operator";
	CONSOLE_MOCK_EMAIL?: "local-operator@agentpass.test";
	ACCESS_TENANT_CLAIM: "custom.tenant_id";
	CONSOLE_STATIC_TENANT_ID?: "refund-demo-agent";
	CONSOLE_STALE_AFTER_SECONDS: "300";
	AGENT_WORKSPACES: DurableObjectNamespace<import("./src/entry").AgentWorkspace>;
	MCP_REGISTRY: DurableObjectNamespace<import("./src/entry").McpRegistry>;
	RECURRING_WORKSPACES: DurableObjectNamespace<import("./src/entry").RecurringWorkspace>;
	AGENTID_GATEWAY: Fetcher /* agentid-gateway */;
	NOTIFICATION_EMAIL?: SendEmail;
	NOTIFICATION_FROM_EMAIL?: "alerts@agentaction.dev";
	CONSOLE_DIRECTORY_MODE?: "true";
	ACCESS_TEAM_DOMAIN?: "https://upperhandteam.cloudflareaccess.com";
	ACCESS_AUD?: "5290e8fbe89e673417d9d8a317ccb28f86c7bfb125d50f03c969dd351f6033c5";
	ACCESS_ROLE_CLAIM?: "custom.tenant_role";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry");
		durableNamespaces: "AgentWorkspace" | "McpRegistry" | "RecurringWorkspace";
	}
	interface DevelopmentEnv {
		AGENT_AI: Ai;
		CONSOLE_ENVIRONMENT: "development";
		CONSOLE_ENABLE_MOCK_IDENTITY: "true";
		CONSOLE_MOCK_TENANT_ID: "refund-demo-agent";
		CONSOLE_MOCK_SUBJECT: "local-operator";
		CONSOLE_MOCK_EMAIL: "local-operator@agentpass.test";
		ACCESS_TENANT_CLAIM: "custom.tenant_id";
		CONSOLE_STATIC_TENANT_ID: "refund-demo-agent";
		CONSOLE_STALE_AFTER_SECONDS: "300";
		AGENT_WORKSPACES: DurableObjectNamespace<import("./src/entry").AgentWorkspace>;
		MCP_REGISTRY: DurableObjectNamespace<import("./src/entry").McpRegistry>;
		RECURRING_WORKSPACES: DurableObjectNamespace<import("./src/entry").RecurringWorkspace>;
		AGENTID_GATEWAY: Fetcher /* agentid-gateway */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
