/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=console/wrangler.readiness.jsonc --include-runtime=false --env-interface=ReadinessEnv console/src/readiness-env.d.ts` (hash: fd1dcdf04c53e455fbacf298e777508f)
interface __BaseEnv_ReadinessEnv {
	CHECK_LIMITER: RateLimit;
	MCP_READINESS: DurableObjectNamespace<import("./readiness-worker").McpReadiness>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./readiness-worker");
		durableNamespaces: "McpReadiness";
	}
	interface Env extends __BaseEnv_ReadinessEnv {}
}
interface ReadinessEnv extends __BaseEnv_ReadinessEnv {}
